[features]
seeds = false
skip-lint = false
[programs.localnet]
puppet = "66Y4xayJiZSNDezxUQFgn6g63nP2D8TnGktB5d1adB9e"
puppet_master = "D43pW9bDogqX6qAco6D8GscTBv3i4yih4TAfi6hLRiHd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/damis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
