[features]
seeds = false
skip-lint = false
[programs.localnet]
game = "3XHPJVeBY7SBFskra4f6fZshB3WvsLr41ETAGTsSQwZJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/damis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
