[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow_headon_attempt = "557jTvF33E6y2rBk9rXVbLDtSepABhpdvNRm8JssSJKi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "/home/damis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
