[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow_headon_attempt = "3uP14PZrmaTpf8UCsvekxQuxct1Q9q4KK9qKqkPSYFLH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/damis/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
